#
# Global routes configuration.
#
# This file contains all routes for the application. It also includes route configuration resources in from the
# routes/ directory. These files bundle routes that are related to each other.
#

#
# All unauthorized index (homepage) routes.
#
homepage_unlocalized:
  path: /
  controller: App\Controller\Welcome\WelcomeController::index

homepage:
  path: /{_locale}
  controller: App\Controller\Welcome\WelcomeController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

homepage_nl:
  path: /nl
  controller: App\Controller\Welcome\WelcomeController::index

homepage_fy:
  path: /fy
  controller: App\Controller\Welcome\WelcomeController::index

#
# All administrator related routes.
#
admin_index:
  resource: 'routes/administrator.yaml'

#
# All Spectator related routes.
#
spectator:
  resource: 'routes/spectator.yaml'

#
# All Teacher related routes.
#
teacher:
  resource: 'routes/teacher.yaml'

#
# All Student related routes.
#
student:
  resource: 'routes/student.yml'

#
# All routs related to Authentication and authorization.
#
authentication:
  resource: 'routes/authentication.yml'
